apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a6a4vyv5s-java-quarkus
  janus-idp.io/tekton: a6a4vyv5s-java-quarkus
  backstage.io/kubernetes-id: a6a4vyv5s-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a6a4vyv5s-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
